#ifndef _MPU_CONFIG_H_
#define _MPU_CONFIG_H_

#include "std_types.h"
#include "loader/elf.h"

#ifndef DISABLE_DEVICE_VDEV
#define MPU_CONFIG_REGION_NUM		UINT_C(8)
#else
#define MPU_CONFIG_REGION_NUM		UINT_C(7)
#endif

#define MPU_ADDRESS_REGION_INX_INTC		(0U)
#define MPU_ADDRESS_REGION_INX_TIMER	(1U)
#define MPU_ADDRESS_REGION_INX_SERIAL	(2U)
#define MPU_ADDRESS_REGION_INX_CAN		(3U)

#ifndef DISABLE_DEVICE_VDEV
#define MPU_ADDRESS_REGION_INX_VDEV		(4U)
#define MPU_ADDRESS_REGION_INX_PH0		(5U)
#define MPU_ADDRESS_REGION_INX_PH1		(6U)
#define MPU_ADDRESS_REGION_INX_CPU		(7U)
#else
#define MPU_ADDRESS_REGION_INX_PH0		(4U)
#define MPU_ADDRESS_REGION_INX_PH1		(5U)
#define MPU_ADDRESS_REGION_INX_CPU		(6U)
#endif

#define ELF_MACHINE_TYPE	EM_V800


#endif /* _MPU_CONFIG_H_ */
